name = "image-uploader"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[build]
command = "npm run build"
watch_dir = "src"

[build.upload]
format = "service-worker"

[pages]
build_output_directory = "dist"

# 确保 Worker 有权限访问 R2
[[migrations]]
tag = "v1"
new_classes = ["R2"] 